//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contestants
    {
        public int numCon { get; set; }
        public string userNameCont { get; set; }
        public Nullable<int> passCont { get; set; }
        public string nameCont { get; set; }
        public string familyCont { get; set; }
        public string nameCompanyCont { get; set; }
        public Nullable<int> Seniority { get; set; }
        public Nullable<int> codeCategory { get; set; }
        public string addressCont { get; set; }
        public Nullable<int> phoneCont { get; set; }
        public Nullable<int> tellOfiiceCont { get; set; }
        public string emailCont { get; set; }
        public string area { get; set; }
    }
}
