//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Editors
    {
        public int numEditor { get; set; }
        public Nullable<int> passEditor { get; set; }
        public string nameEditor { get; set; }
        public string familyEditor { get; set; }
        public string addressEditor { get; set; }
        public string emailEditor { get; set; }
        public Nullable<int> phoneEditor { get; set; }
        public Nullable<int> tellOfiicEditor { get; set; }
    }
}
