//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class DbtenderEntities1 : DbContext
    {
        public DbtenderEntities1()
            : base("name=DbtenderEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Contestants> Contestants { get; set; }
        public virtual DbSet<ConToTender> ConToTender { get; set; }
        public virtual DbSet<Editors> Editors { get; set; }
        public virtual DbSet<TypeTender> TypeTender { get; set; }
        public virtual DbSet<SuggestionDetail> SuggestionDetail { get; set; }
        public virtual DbSet<SiteMenu> SiteMenu { get; set; }
        public virtual DbSet<ClientMenu> ClientMenu { get; set; }
        public virtual DbSet<Suggestions> Suggestions { get; set; }
        public virtual DbSet<ProducToTender> ProducToTender { get; set; }
        public virtual DbSet<Tenders> Tenders { get; set; }
    
        public virtual ObjectResult<ss_Result> ss()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ss_Result>("ss");
        }
    }
}
