//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Suggestions
    {
        public int numSuggestion { get; set; }
        public int numTender { get; set; }
        public Nullable<int> numCont { get; set; }
        public Nullable<int> priceToproduct { get; set; }
        public Nullable<System.DateTime> dataSuggestion { get; set; }
        public Nullable<System.TimeSpan> timeSuggestion { get; set; }
        public string percentOff { get; set; }
    }
}
