//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SuggestionDetail
    {
        public int numDetailSuggestion { get; set; }
        public Nullable<int> numsuggest { get; set; }
        public Nullable<int> numproduct { get; set; }
        public Nullable<int> priceToProduct { get; set; }
    }
}
