//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace tender.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tenders
    {
        public int numTender { get; set; }
        public string name { get; set; }
        public Nullable<int> numType { get; set; }
        public Nullable<int> numEditor { get; set; }
        public Nullable<int> codCategory { get; set; }
        public string typeAcquire { get; set; }
        public string status { get; set; }
        public Nullable<System.DateTime> from { get; set; }
        public Nullable<System.DateTime> till { get; set; }
        public Nullable<System.TimeSpan> hourStart { get; set; }
        public Nullable<System.TimeSpan> hourFinish { get; set; }
    }
}
